### ISSUE TITLE
Getting current depth while navigating through a tree-like structure

### ISSUE THREAD

**Issue by robhanlon22** [redplanetlabs/specter#319]
Let's say I have a tree structure like this:

```clojure
{:value 1 :children [{:value 2 :children []} {:value 3 :children [{:value 4 :children []}]}}]
```

Now, let's say I want to do something only on nodes with a depth of 1, i.e. the nodes with values 2 and 3. Is this possible using `collect`, a `recursive`, or `walker`? Or is there just something I'm not thinking of? Thanks in advance :)

**Comment by nathanmarz** [comment]
If all you care about is nodes at depth 1, then you can just use the path `[:children ALL]`. For other depth values, you could dynamically construct a path targeting only that depth using `comp-navs` to compose multiple `(path :children ALL)` together. Otherwise, the generic technique for keeping track of your depth in a recursive path is to use value collection and then to check the number of collected values with `collected?`.
