### ISSUE TITLE
Redo documentation

### ISSUE THREAD

**Issue by nathanmarz** [redplanetlabs/specter#56]
Right now the "docs" are spread out over a blog post, youtube video, and examples on the README. They are also incomplete. The wiki for this repository should consolidate existing information and be extended with more docs. Two kinds of documentation are needed most:
- Overview of features: navigation, selection, transformation, replace-in, protocol to make new navigators,  higher-order navigators, precompilation, late-bound parameterization, recursive navigation, protocol paths
- Reference documentation for built-in navigators: Should describe what they do and provide examples of usage.

**Comment by nathanmarz** [comment]
Also need to document the zipper integration and provide examples that can be handled with zipper navigators that can't be handled by the typical navigators (ALL, keywords, etc.)

**Comment by luxbock** [comment]
I think the biggest problem with the current state of documentation (using the source code as the docs) is that because specter has so many features, it's a bit difficult to tell what the core API functions/macros of specter are, especially since now they are split across multiple files, and currently `transform`, `select`, `collect` etc. don't have any doc strings at all.

**Comment by nathanmarz** [comment]
Generated API docs: http://nathanmarz.github.io/specter/

**Comment by gdeer81** [comment]
A recipe book would be fantastic although the only person with enough experience with the library to write one probably doesn't have the time. 

I'm working on some Specter Koans since I find the guided path the easiest to follow.  
It would start off with simple select statements then transforms and eventually have the user writing custom navigators. I'll try to cover the whole API.

**Comment by nathanmarz** [comment]
@gdeer81 That would be great

**Comment by gdeer81** [comment]
@nathanmarz https://github.com/gdeer81/specter-koans It's alive
I actually learned a lot writing it

The most difficult part is thinking of interestingly hairy data structures.

Also, I'm not sure how readable the problems are with the nested collections inlined with the problems.
I used let bindings so I could refer to it by name but then my tests went from
`(= __ (form-to-contemplate))`
and started looking like 
`(let [hairty-coll {{{{{{{...so much stuff..}}}}}}}] (= __ (select [ALL] hairy-coll)`
I like having the blank hanging out to the far left and all the action happening on the other side.

In the next set of problems I might try deffing all the forms in the beginning and see if it makes the problems more readable or if its annoying having to refer back to the top of the file

The other thing I want to make sure is that the problems are good. Like I said, I'm learning a lot writing this but I want to make sure I'm presenting the library properly.

For each track I'm going to be scraping blogs, your talks, and examples from the documentation to get a solid set of problems.

Of course, if you have good examples all I need is <Specter form> <Hairy Data Structure> and I can convert it into a koan

**Comment by nathanmarz** [comment]
@gdeer81 Great, as you make more I can look through and give you feedback.

FYI, I tried running it myself but I get this error:

```
Now meditate upon /Users/nathan/opensource/specter-koans/src/koans/01_selection.clj
---------------------
Assertion failed!
clojure.lang.ExceptionInfo: We shall contemplate selection by exploring navigation, first ALL
(= __ (= [1 2 3] (select [ALL] [1 2 3]))) {:line 7}, compiling:(/Users/nathan/opensource/specter-koans/src/koans/01_selection.clj:5:1)
```

**Comment by souenzzo** [comment]
Give a tip for specter users that on clojurescript, they should care about `require`/`require-macros`

Some usable examples like

`(:require [com.rpl.specter :refer :all :refer-macros :all])`

`(:require [com.rpl.specter :as s :refer-macros [select transform]])`

**Comment by nathanmarz** [comment]
The specter wiki is now in its own repository so that pull requests can be made to it: https://github.com/nathanmarz/specter-wiki

Also, the issue tracker on that project can be used to record anything that needs to be improved in Specter's documentation.

**Comment by nathanmarz** [comment]
A visualization tool for how navigators move through a data structure would be helpful, something like highlighting which parts of a data structure are currently navigated to as you move through a path.

Something that wouldn't be as good but would be easy to implement would be a `visualize-path` command that simply reduces through the path, showing what is navigated at each step. Example output:

```
(visualize-path [ALL :a even?] [{:a 1 :b 2} {:a 2} {:a 4}])

START
[{:a 1 :b 2} {:a 2} {:a 4}]

ALL
{:a 1 :b 2}
{:a 2}
{:a 4}

:a
1
2
4

even?
2
4
```

Getting this to visualize recursive paths and higher-order navigators in a useful way would be substantially harder, though just a basic implementation should still be helpful.

**Comment by gdeer81** [comment]
@nathanmarz I just now saw your comment about the koans failing when you tried to run it. That's how it is supposed to work. You were supposed to go to `/Users/nathan/opensource/specter-koans/src/koans/01_selection.clj` and look at line 7
you will see the code that it showed in the error message: `(= __ (= [1 2 3] (select [ALL] [1 2 3])))`
so then you fill in the blank so it looks like this `(= true (= [1 2 3] (select [ALL] [1 2 3])))` since that expression evaluates to true
Then when you save the file you'll get another error that will say
`clojure.lang.ExceptionInfo: To understand selection you must understand navigation
(= __ (count (select [ALL odd?] [1 2 3]))) {:line 10}, compiling:(/Users/nathan/opensource/specter-koans/src/koans/01_selection.clj:5:1)`

So you do the same thing, fill in the blank and save. If you put the correct answer in the blank it will move on to the next meditation that is blank, else it will stay on the current one until you have filled in the correct answer.

The answers are stored in koans.clj if you want to play around with it

**Comment by nha** [comment]
@gdeer81 I started playing with your koans. Looks great! One thing I was expecting is to fill in the blanks myself, not just true/false.
Ie. in your example above, I think it would be more useful to have the blanks like that:
```
 (= __ (select [ALL] [1 2 3]))
```
It would make me think a little bit harder, not just guess if it looks alright or not but actually think about what it means and does. In my case I think would make me integrate/remember things better.

**Comment by DjebbZ** [comment]
In addition to 

> Overview of features: navigation, selection, transformation, replace-in, protocol to make new navigators, higher-order navigators, precompilation, late-bound parameterization, recursive navigation, protocol paths

it would be very nice to have the API into a cheat-sheet, like https://clojure.org/api/cheatsheet and http://clojuredocs.org/quickref. The bonus point of a cheat-sheet is that you have to categorize it precisely, in a very fined-grained way. 

I think the part I quoted just above is not even enough, because I'm sure that there are even other kind of functionality inside specter. Like collection (from `collect`) which I consider slightly different from selection, removal (`NONE`), indexed navigation vs. keyed navigation, predicates etc. So the first step would be to list `ALL` (see the pun?) of them concepts/functionality that are used in Specter, whether they're part of Specter or not (think data-structures for examples). Then define them, then categorize all APIs under those.

I'm willing to give a hand in the limits of my time, ability and understanding of Specter.

**Comment by nathanmarz** [comment]
@DjebbZ That's a good idea. Such a cheatsheet could categorize most navigators by data structure type. An incomplete list:

Maps - `keypath`, `must`, `ALL`, `MAP-VALS`, `MAP-KEYS`, `submap`
Sequences - `nthpath`, `ALL`, `filterer`, `srange`, `srange-dynamic`, `continuous-subseqs`, `BEFORE-ELEM`, `AFTER-ELEM`, `before-index`, `FIRST`, `LAST`
Sets - `subset`, `NONE-ELEM`
Keywords/symbols - `NAME`, `NAMESPACE`

Then there are other kinds of navigators which aren't data structure specific, e.g. `if-path`, `multi-path`, `subselect`, and `view`. Those could be categorized separately.

**Comment by DjebbZ** [comment]
That's a good beginning.

As a relative beginner to Specter (even if I managed to write a recursive navigator), I don't see value in categorizing by data structures only. If you look carefully at both cheatsheets I linked above, they group APIs sometimes by concrete data structures, sometimes by abstractions over data structures (sequences), sometimes by types of operations (flow control, concurrency, Java Interop etc.) etc. Then subgroup once, sometimes twice into more fine grained category : create, 'change', use, etc.

The goal IMHO would be to find both the proper vocabulary with respect to the current code base and names already chosen *and* the proper categorization. I love naming things, so I'd be extremely happy to review what you can come up with Nathan. I can try in my own, but my limited knowledge of Specter prevents me to cover everything.

I hope you appreciate (and agree!) with this proposal. At the end of the day I just want to become proficient with Specter, so much power and expressiveness here.

**Comment by nathanmarz** [comment]
We're on the same page. Most of the navigators categorize by data structure, while the rest can have their own categorizations. Here's a list of categories which cover pretty much all of the navigators:

Maps
Sequences
Sets
Keywords/symbols
Atoms
Strings
Filters (e.g. `pred`, `selected?`)
Views (e.g. `view`, `transformed`, `traversed`, `NIL->VECTOR`)
Control (e.g. `if-path`, `multi-path`, `stay-then-continue`, `STAY`, `STOP`)
Value collection (e.g. `DISPENSE`, `collect-one`, `collected?`)
Multi-transform (`terminal`, `terminal-val`)

Some navigators belong in multiple categories and thus should be listed multiple times (e.g. `srange` for sequences and strings, `ALL` for maps, sequences, and sets).

**Comment by DjebbZ** [comment]
Great, it's getting better.

I see you didn't reuse the category "replace-in" you mentionned earlier. I found it useful.

One small confusion though: there's no API specific to sets as sets are sequences, right? Also, the wiki mentions navigators for collections, but you didn't mention them above. I think it's useful to have collection as a kind of category (as a data structure) since it encompasses all Clojure's compound data structures.

A problem I see in putting data structures and others at the same level of categorization is that data structures are the _object_ we operate on whereas the rest is the _kind_ of navigation/operation we use on the _object_. This distinction is more easily materialized if we use "nouns" for the _objects_ and verbs for the _kinds_ of operation. So for me most (if not all) navigators will have at least one data structure _and_ one navigator/operation. Ex: the first of the wiki `AFTER-ELEM` is a navigator on sequences (maps too?) which has the role of "replace-in". That's how I see it at least. Of course no need to be extremist if a word (or a few words) is better than a verb for instance. but I think it's the general direction to follow.

For the record I tried using the categories you mentioned to categorize all the navigators from the Navigators Wiki page, but stopped because:
- it's getting late here, I need to sleep
- I think we're too early in the discussion to try a draft

As I was trying to categorize I realized that several navigators have a different behavior when used in queries and in transforms. Not sure how to best materialize the difference yet. Ex: `AFTER-ELEM` makes almost no sense in queries since it returns `com.rpl.specter.impl/NONE` (so it's a not a "syntax" error to use it) but is useful in transforms.

Now on what's called macros in Specter. I think the naming is poor because it's a feature of Clojure and doesn't tell anything about their role in Specter. The README uses the term "operations" and then distinguish queries and transforms which is already much better. Although the wiki dedicated to them also use the wording "selection operations" for queries, which is fine too. Just need to choose one.

Then there are "macros" that are neither queries or transform: 
- `collected?`: it's used in paths like another navigators, so putting it into the macros page feels weird. I think you put it there from a technical point of view (it's a Clojure macro), but from a semantic point of view it makes little sense.
- the various `def`. There is some categorization already in the dedicated wiki page but it's still about macros. Maybe a wording like "Defining your own paths/navigators" or "Custom paths/navigators".

The last point raises a concern: 
Paths and navigators definitely need some definition. Below my current understanding in pseudo BNF style (far from a complete definition):

```
Usage: (Operation Path Data)
Operation: Query|Transform
Path: Navigator|Vector of Navigators
Data: User provided data structure to operate on.
```

Now I know all "macros" are not like this, but it helps to have a kinda formal definition of what an operation is and what a path is (this one is really useful). Of course the wording depends of all the categorization work above, so take it as a hint and not a proposal at all.

End of the comment it's really late for me. Looking forward to see your thoughts.

**Comment by nathanmarz** [comment]
`replace-in` is an operation like `select`/`transform`, not a category.

Sets are not sequences. Specter's set-specific navigators are `NONE-ELEM`, `subset`, and `set-elem`. 

I think "query" makes sense as a general term for `select`, `traverse`, `select-any`, etc.

In my last comment I was just outlining a categorization for navigators, but it does make sense for a cheat sheet to include the operations as well: `select`, `select-any`, `select-one`, `select-one!`, `traverse`, `transform`, `setval`, `vtransform`, `replace-in`. Makes sense to split a cheat sheet into two sections, one for operations and one for navigators. 

`collected?` should be included under navigators section for "Value collection" category.

Regarding `AFTER-ELEM`, it's true that it is only really useful for transforms. But it still has sensible navigation behavior for queries. (and it's only for sequences)

There could be a final section on the cheat sheet for everything available for making new navigators: `defnav`, `defrichnav`, `late-bound-nav`, `defdynamicnav`, etc.

**Comment by DjebbZ** [comment]
Based on your feedback I'm going to work on an outline of a cheatsheet. Will get back here, hopefully soon.

**Comment by nathanmarz** [comment]
@DjebbZ Great! The specter wiki is in its own repository and you can make a pull request there: https://github.com/nathanmarz/specter-wiki

**Comment by DjebbZ** [comment]
Truth is, every GitHub with a wiki has special repo where you suffix it
with `.wiki`, no need to create it.

So I already cloned locally from https://github.com/nathanmarz/specter
<https://github.com/nathanmarz/specter-wiki>.wiki

I hope to have something to show by the end of the day.

Le 11 févr. 2018 05:12, "Nathan Marz" <notifications@github.com> a écrit :

@DjebbZ <https://github.com/djebbz> Great! The specter wiki is in its own
repository and you can make a pull request there:
https://github.com/nathanmarz/specter-wiki

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nathanmarz/specter/issues/56#issuecomment-364719307>,
or mute the thread

**Comment by DjebbZ** [comment]
Here we go https://github.com/nathanmarz/specter-wiki/pull/26

(The `.wiki` trick is a bad idea, impossible to fork it and push my changes...)

**Comment by DjebbZ** [comment]
Another idea: a glossary of all Specter concepts. Based on this:

> Overview of features: navigation, selection, transformation, replace-in, protocol to make new navigators, higher-order navigators, precompilation, late-bound parameterization, recursive navigation, protocol paths

I would also add the concept of a `view` to this list.

Willing to give a hand here too after the initial work on a cheat sheet is finished.

**Comment by nathanmarz** [comment]
Sure, that would be great.

**Comment by marksto** [comment]
@nathanmarz Hi Nathan! It seems that Cheat Sheet link for `vtransform` is broken and the docs for this macro are still missing.
